name: fast5_to_pod5
description: Convert fast5 files to fastq files
keywords:
  - ONT
  - Oxford
  - Nanopore
  - fastq
tools:
  - pod5:
      description: |
        POD5 is a file format for storing nanopore sequencing data in an
        easily accessible way. The format is able to be written in a 
        streaming manner which allows a sequencing instrument to directly 
        write the format.
      homepage: https://github.com/nanoporetech/pod5-file-format
      documentation: https://pod5-file-format.readthedocs.io/en/0.1.21/index.html
      licence: ["MPL-2.0"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fast5:
      type: path
      description: |
        Path where the fast5 files are located
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - pod5:
      type: file
      description: Pod5 converted files
      pattern: "*_{converted.pod5}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

